import type { User, Document, Activity } from "@/types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Dr. Ahmad Hasnur",
    email: "admin@hafecs.org",
    role: "admin",
    department: "Manajemen",
    createdAt: "2024-01-15",
    isActive: true,
  },
  {
    id: "2",
    name: "Siti Nurhaliza",
    email: "staf@hafecs.org",
    role: "staf",
    department: "Administrasi",
    createdAt: "2024-02-01",
    isActive: true,
  },
  {
    id: "3",
    name: "Budi Santoso",
    email: "hode@hafecs.org",
    role: "hode",
    department: "Pelatihan",
    createdAt: "2024-01-20",
    isActive: true,
  },
  {
    id: "4",
    name: "Rina Kartika",
    email: "rina@hafecs.org",
    role: "staf",
    department: "Pelatihan",
    createdAt: "2024-02-10",
    isActive: true,
  },
  {
    id: "5",
    name: "Agus Wijaya",
    email: "agus@hafecs.org",
    role: "staf",
    department: "Administrasi",
    createdAt: "2024-02-15",
    isActive: false,
  },
]

export const mockDocuments: Document[] = [
  {
    id: "1",
    type: "surat",
    title: "Surat Undangan Pelatihan Digital",
    code: "SEC",
    number: "SEC/001/03/2024",
    content: "Undangan pelatihan kompetensi guru digital...",
    status: "approved",
    createdBy: "2",
    createdByName: "Siti Nurhaliza",
    approvedBy: "3",
    approvedByName: "Budi Santoso",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-02",
  },
  {
    id: "2",
    type: "sertifikat",
    title: "Sertifikat Pelatihan Teknologi Pendidikan",
    content: "Sertifikat untuk 25 peserta pelatihan...",
    status: "pending",
    createdBy: "4",
    createdByName: "Rina Kartika",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-05",
    participants: ["Ahmad Budiman", "Siti Aminah", "Budi Raharjo"],
  },
  {
    id: "3",
    type: "surat",
    title: "Surat Pemberitahuan Jadwal",
    code: "PRT",
    number: "PRT/045/03/2024",
    content: "Pemberitahuan perubahan jadwal pelatihan...",
    status: "draft",
    createdBy: "2",
    createdByName: "Siti Nurhaliza",
    createdAt: "2024-03-10",
    updatedAt: "2024-03-10",
  },
]

export const mockActivities: Activity[] = [
  {
    id: "1",
    userId: "2",
    userName: "Siti Nurhaliza",
    action: "Membuat surat",
    target: "SEC/001/03/2024",
    timestamp: "2024-03-01 09:30",
    details: "Surat undangan pelatihan digital",
  },
  {
    id: "2",
    userId: "3",
    userName: "Budi Santoso",
    action: "Menyetujui surat",
    target: "SEC/001/03/2024",
    timestamp: "2024-03-02 14:15",
  },
  {
    id: "3",
    userId: "4",
    userName: "Rina Kartika",
    action: "Membuat sertifikat",
    target: "Sertifikat Pelatihan Teknologi",
    timestamp: "2024-03-05 11:20",
    details: "25 peserta",
  },
]
